org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC

# Найстрокйи проекта
java_version=21
project_group=com.zfettostudios.zjtime
project_name=zJTime
project_version=0.1.2
project_authors=zFetto Studios
project_website=https://zfettostudios.com/project/zfuctone
project_description=A Java library for easier time handling

# Lombok
# https://projectlombok.org/
# https://repo.maven.apache.org/maven2/org/projectlombok/lombok/
lombok_version=1.18.48

# Gradle Shadow
# https://plugins.gradle.org/m2/com/gradleup/shadow/com.gradleup.shadow.gradle.plugin/
gradle_shadow_version=9.6.1